name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Cargo build
      run: cargo build

    - name: Cargo test
      run: cargo test

    - name: Install Cargo clippy
      run: rustup component add clippy && cargo clippy
